### ISSUE TITLE
NameError: name 'self' is not defined is npyscreenreactor

### ISSUE THREAD

**Issue by dummys** [mtearle/npyscreenreactor#4] opened 2016-01-08 15:26 UTC
Hi, your client code is not working:

Traceback (most recent call last):
  File "EXAMPLE-npyscreenreactor-client.p_oldy", line 20, in <module>
    import npyscreenreactor
  File "/home/mofo/works/perso/b4db0t/npyscreenreactor/__init__.py", line 38, in <module>
    class NpyscreenReactor(selectreactor.SelectReactor):
  File "/home/mofo/works/perso/b4db0t/npyscreenreactor/__init__.py", line 49, in NpyscreenReactor
    selectreactor.SelectReactor.doIteration(self, timeout)  # push event back on the npyscreen queue
NameError: name 'self' is not defined

**Comment by mtearle** [comment] 2016-01-09 02:32
Hi

I've just done a clean install on a brand new VM and I can't duplicate this installing from the github repository.

Can you give me some more information about your install?  What version did you download/install?  

The kind of error that you've provided feels like the init.py may have been corrupted (and the indentation munged)

**Comment by dummys** [comment] 2016-01-11 16:28
Using a virtualenv with a fresh git clone or your stuff:
pip install npyscreen npyscreenreactor

/home/user/works/env_npyscreen/bin/python EXAMPLE-npyscreenreactor-client.py 
  File "EXAMPLE-npyscreenreactor-client.py", line 37
    self.app.line_to_buffer(line)
                                ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by dummys** [comment] 2016-01-12 12:14
no idea?  what, did you do to make it work?  Are you using python 2 or 3?

**Comment by mtearle** [comment] 2016-01-12 15:32
I've been using python 2.    

The second error trace you've given notes issues with mixes of tab and spaces.  Python 3 is more picky with the behaviour of tabs and spaces (see the answer here - http://stackoverflow.com/questions/18225712/taberror-in-python-3 )

I've checked the example, and yes, there is a mix of tabs and spaces.

This should be a quick and easy fix to adjust the indentation across the reactor and the examples.
I'll spend some time fixing things tomorrow evening and push to the repository.  (patches welcome if want to fix it yourself in the interim)

**Comment by dummys** [comment] 2016-01-12 18:41
Ok I made a pull request

**Comment by mtearle** [comment] 2016-01-13 19:54
I've committed a fix to the indentation to the head of my repository. 

Can you please pull this and test?

I'll try and do some more testing in a test VM/virtualenv before closing the issue once I get some feedback.

**Comment by dummys** [comment] 2016-01-14 09:27
Hello,

The reactor stuff is ok. I also use a virtualenv. I get an error when connecting from the client in the server log:

![fail](https://cloud.githubusercontent.com/assets/1941445/12320533/6955adf2-baa9-11e5-9020-e7058d56b71d.png)

**Comment by mtearle** [comment] 2016-01-17 15:27
A quick update.  I've setup a python3 virtualenv and have managed to replicated this.   Will investigate the cause in more over the next couple of days.

**Comment by dummys** [comment] 2016-01-21 08:02
hello, no news ?

**Comment by mtearle** [comment] 2016-01-21 09:57
Apologies, have been snowed under at work this week.  Will try and catch the twisted developers on IRC as I need some advice tonight.

**Comment by mtearle** [comment] 2016-01-24 13:45
Have had some time to work on this thoroughly.   Both the client and server examples should work now.

Can you test?

**Comment by mtearle** [comment] 2016-01-30 03:02
Noting as resolved and new release made.

**Closed by mtearle** 2016-01-30 03:02 UTC
Labels: bug
